#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../../bash/include.sh"

success "Executing: npm install"
npm install
success "Executing: npm prune"
npm prune

success "All done."
