#!/bin/bash

DIR="$(cd $(dirname $(git rev-parse --git-dir)) && pwd)"
source "${DIR}/bash/include.sh"
cd "${DIR}"

success "Executing: npm install"
npm install
success "Executing: npm prune"
npm prune

success "All done."
