#!/bin/bash

DIR="$(dirname $(git rev-parse --git-dir))"
source "${DIR}/bash/include.sh"
cd "${DIR}"

success "Executing: npm install"
npm install
success "Executing: npm prune"
npm prune

success "All done."
